### ISSUE TITLE
Position of camera in assignment 2

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#20]
The starter code seems to put the origin at (-1, 1, 1), and the comment is "The camera is perspective, pointing in the direction -z and covering the unit square (-1,1) in x and y".

To me, it seems like the camera is on the plane of the pixels, if it is on the unit square (-1, 1).  However, in class, it looked like the drawings showed the camera centered on the pixels, and was a bit removed from the plane of the pixels.  Where exactly is the camera?

**Comment by arvigj** [comment]
The sketch in the slides is correct and the location of the ray origin in the plane of the pixels is meant to be fixed by you in the assignment. It is up to you where you put it (within reason, so you can resolve the scene), but you can play around with its placement to get an intuition about perspective projection.

**Comment by jessberg** [comment]
Then what does it mean that the camera covers the unit square (-1, 1) in x and y?

**Comment by arvigj** [comment]
This means that the image you need to output needs to be the scene projected onto the unit square (x goes from -1 to 1, so does y) with respect to the chosen ray origin.
