### ISSUE TITLE
Getting some empty patches in the Ray Traced Dragon

### ISSUE THREAD

**Issue by khandu-utkarsh** [danielepanozzo/cg#32]
Hi 

I implemented bounded box intersection check and AABB tree for rendering dragon and bunny. It seems to be working fine for the bunny, but the final image that I am getting for the dragon has some empty patches. Since both of these are using precisely the same algorithm, I am not able to understand why there is a difference then. 

So, is this some error?

If yes, what can be the probable causes for this?

![raytrace_bunny_bvh](https://user-images.githubusercontent.com/60479858/138542072-72c49996-3abc-41d1-ab67-c6fbed7b8e25.png)
 

![raytrace](https://user-images.githubusercontent.com/60479858/138542035-cca06101-7a2e-4c7b-b2d8-d3226d3926d7.png)

**Comment by danielepanozzo** [comment]
Something is wrong, there should not be gaps. I suggest the following to debug:
1. Identify a region that has the problem (for example in the head), the smaller the region the better.
2. Rerun the raytracing there *without* the acceleration data structure. Since the region is small, you should be able to do this in reasonable time. If the two images are different, pick a pixel that is different and then debug it to find out why some triangles are missed.

If this does not work, let's meet in the office hour tomorrow and I will see if I can come up with a different strategy.

**Comment by khandu-utkarsh** [comment]
Thanks for your response Professor!
I will try this strategy.

**Comment by khandu-utkarsh** [comment]
@danielepanozzo 

I used this strategy to isolate the problem at the smallest level. Found some issues with my triangle ray intersection function. Fixed it and it seems to be working great!

Thanks!
