### ISSUE TITLE
Segmentation fault with solver

### ISSUE THREAD

**Issue by DebraChait** [danielepanozzo/cg#34]
My program compiles, but I get a segmentation fault when I call the solver for a system of linear equations:

Vector3d x = A.colPivHouseholderQr().solve(bmat);

I have defined A with type Matrix3d and bmat with type Vector3d. What might be going wrong here? I did not have any problems when I used this in my last assignment.

**Comment by danielepanozzo** [comment]
Did you try running the program in debug mode? It is possible the problem is somewhere else.

If it runs fine in debug, could it be that your system is singular and does not have a solution? Could you print A and bmat and try to solve the same linear system in isolation and check if it has a solution?

**Comment by DebraChait** [comment]
It turned out to be a bug somewhere else that I found in debug. Thank you!
