### ISSUE TITLE
Diffuse light in rasterization

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#50]
I am trying to transfer my specular and diffuse lighting equations from assignment 2 for the flat shading part of assignment 4.  I believe the light direction should now be the light position minus the ray_intersection, normalized.  However, in rasterization, there is no ray.  Should you still be computing the intersection of the light ray and the triangle in order to calculate the lighting?  Is the position and location of the light and view direction part of the uniform?

**Comment by danielepanozzo** [comment]
You can think of rasterization as tracing one ray for every pixel, and figure out if it hits a triangle or not. We do not do it explicitly by tracing a ray, but we could have, it would have just been more expensive.

The "point of intersection" is simply the position of the fragment (which you can get by barycentric interpolation of the position of the three vertices).

Position of light and camera parameters should be uniform, as they are they same for all the rendered primitives.

**Comment by jessberg** [comment]
I'm a bit confused still on the position of the fragment.  The input to the fragment shading function is va, which I took to mean vertex attributes.  Are these the vertex attributes interpolated?  So va.position is the position of the fragment?

**Comment by danielepanozzo** [comment]
yes, the input to the fragment shader is a struct containing the attributes defined at the vertices interpolated using the barycentric coordinates of the fragment.

**Comment by jessberg** [comment]
Then the lighting will change for different points in the same fragment.  If the position is interpolated, then it changes, and so the light direction, which is determined by the position and light, changes.  Then diffuse lighting uses the normal dot the light direction, so the diffuse lighting will change for different points on the same fragment.  How do you get only one value for flat shading when this is constantly changing?

**Comment by danielepanozzo** [comment]
I think I understand where the confusion is coming from. The color can be computed either on the vertex or fragment shader.

The assignment is asking to do the computation of the color in the vertex shader, and then interpolate it in the triangle. This is easier. In flat shading, all 3 vertices use the same normal (i.e. the normal of the triangle), for per-vertex shading, each vertex has its own normal. The fragment shader directly interpolates the color.

What I think you are trying to do, which is also ok and will actually look more similar to the first assignment, is to compute the color in the fragment shader. If you go that way, it is indeed hard to get a single color per triangle. If you decide to go this way, it is fine if you get slightly different colors because the position of the fragment is different.

Hope this clarifies the confusion. I changed the text of the assignment to make this more clear.

**Comment by jessberg** [comment]
Oh, I think I see.  I would rather do it the way the assignment said, so I will move things to the vertex shader.  The issue is that I think the values would still change;  the diffuse color is still dependent on the position, it's just that the position is now different for each vertex.  Then you interpolate those values differently depending on the barycentric coordinates of the pixel.  So you still wind up weighting each vertex's color differently depending on where you are in the triangle.

**Comment by danielepanozzo** [comment]
It is possible to do with a single color: you have to pass, for every vertex of a triangle, the coordinate of the first vertex of the triangle as an additional input. However this is unintuitive and unnecessary. I changed the text of the assignment to clarify that it is enough to use the same normal you do not need to get exactly the same color for every fragment in a triangle.

**Comment by jessberg** [comment]
That makes sense now.  Thank you!
