### ISSUE TITLE
Possible bug of rendering lines in the rasterizer

### ISSUE THREAD

**Issue by jr028740** [danielepanozzo/cg#53]
Dear Professor and TAs,

Sorry to interrupt you! I found a possible bug in the rasterizer when rendering lines. The effect is that when rendering any line parallel to the x or y plane, if the thickness is set smaller or equal to 0.5, these lines will not be able to appear in the rendered image.

Test code for reference:

```C++
vector<VertexAttributes> vertices;
// Line parallel to x plane
vertices.push_back(VertexAttributes(-0.5,-0.5,0));
vertices.push_back(VertexAttributes(0.5,-0.5,0));
// Line parallel to y plane
vertices.push_back(VertexAttributes(0.5,-0.5,0));
vertices.push_back(VertexAttributes(0.5,0.5,0));

// Setting the thickness parameter below or equal to 0.5 will result in showing neither of those two lines
rasterize_lines(program,uniform,vertices,0.5,frameBuffer);
```

**Comment by Huangzizhou** [comment]
It's because a line whose thickness is less than half of the pixel size is not visible. There's an if condition `if ((pixel - pixel_p).squaredNorm() < (line_thickness*line_thickness))` in the `rasterize_line()` to skip lines with too small thickness. The line thickness is a relative value, i.e. 0.5 corresponds to half of the pixel size, so you cannot see it even if you increasing the resolution.

**Comment by jr028740** [comment]
> It's because a line whose thickness is less than half of the pixel size is not visible. There's an if condition `if ((pixel - pixel_p).squaredNorm() < (line_thickness*line_thickness))` in the `rasterize_line()` to skip lines with too small thickness. The line thickness is a relative value, i.e. 0.5 corresponds to half of the pixel size, so you cannot see it even if you increasing the resolution.

Thanks for your clarification!
