### ISSUE TITLE
Perspective projection deriving coordinates

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#64]
I am having some issues getting the coordinates for the perspective matrix.  Slide deck 12 slide 16 says you can derive everything if given n and theta.  It also says tan(theta/2) = t/|n|.  I fail to see how this is true.  There should be two triangles you can take into account:

origin, (0,0,n) and (0,b,n) (the near triangle)
origin, (0,0,f) and (0, t, f) (the far triangle)

So all I can see from the picture is that tan(theta) = t/f, or tan(theta) = b/n.  I don't think you can say anything about the relationship between the two triangles without knowing f-n, and I don't understand how you arrive at tan(theta/2) = t/|n| on the slide.  Could someone explain?

**Comment by danielepanozzo** [comment]
Thank you for finding this. The formula is correct, but the illustrations is not, I will fix the slide. r,t are not the coordinates of the corner of the frustum, they are the coordinates of the box obtained after applying the perspective transformation (these 2 coordinates do not affect the matrix P). Since we are assuming that the user is looking at the center of the box, t=-b and from there tan(theta/2) = t/|n| (we use t instead of b to get a positive sign). If this is still not clear, please take a look at 7.5 in the textbook or we can find time tomorrow to discuss on zoom.
