### ISSUE TITLE
AABBTree bottom-up construction

### ISSUE THREAD

**Issue by MinervaMint** [danielepanozzo/cg#7]
Hello Professor,

Can I ask how long would it normally take to build the AABB tree for the dragon.off in the bottom-up way? I tried my implementation on the bunny.off and it worked, although it took much longer than the top-down approach. But when I use it for the dragon it seems to take forever to build the tree, so I am not sure whether there is something wrong with my implementation. 

I tried the increase of volume and the distance between centroids as the criteria for choosing two nodes to pair. Both attempts failed to build the tree for dragon in acceptable time. It seems in every step I have to scan through all possible nodes to find the pair with the lowest cost, will this be too expensive (especially for the dragon with over 800k triangles)?

Thanks.

**Comment by danielepanozzo** [comment]
Instead of looking for the best pair, I recommend to loop over every nodes and greedly merge it with the closest one. In this way, the complexity is quadratic wrt the number of triangles, which is tolerable for the provided meshes (it will take maybe 20-30 minutes). Another way is to sort the primitives over an axis (as in the top-down construction) and greedly merge adjacent ones after the sorting to further reduce the complexity.  Your algorithm is cubic, and it will likely not finish in a reasonable time for the dragon.

**Comment by MinervaMint** [comment]
Thank you professor!
