### ISSUE TITLE
Assignment 6: Details needed while implementing translation

### ISSUE THREAD

**Issue by khandu-utkarsh** [danielepanozzo/cg#87]
In translation, once we have released the mouse click. The selected triangle should be permanently moved to a new location, right?

For all the further operations, it should be at the new position.
Also, I am currently implementing a translation transformation matrix in the Vertex shader, so once the mouse click has been released, it should update the positions of all vertex in the database (where it is storing triangle positions) and set the translation matrix to Identity, right?

Similar will be for scaling and rotating, right?

Also, I am adding functionality to only select one triangle at a time, do we need to add a mechanism to select multiple triangles simultaneously?

**Comment by Huangzizhou** [comment]
1. Yes, the selected triangle should be permanently moved to a new location.
2. Do not store the translations/scaling/rotations into different matrices, you just need 1 transformation matrix for each triangle, otherwise you may break the order of different transformations. Matrix multiplications are not commutative.
3. You don't need to set matrices to identity when you release the mouse, just accumulate all transformations into the matrix.
4. Just one triangle at a time is fine.

**Comment by khandu-utkarsh** [comment]
Ok.
So there will be one transformation matrix, for every triangle.
